export interface TProduct {
  id: number;
  title: string;
  productNum: number;
  brand: string;
  is_featured: boolean;
  batchNo: string;
  category: string;
  price: number;
  quantity: number;
  subtotal: number;
  tax: number;
  discount: number;
  unit: string;
}

const product_data: TProduct[] = [
  {
    id: 1,
    title: 'Exide Edge Battery',
    productNum: 10123456,
    brand: 'Exide',
    is_featured: true,
    batchNo: '12345678',
    category: 'Automotive Batteries',
    price: 150,
    quantity: 1,
    subtotal: 0,
    tax: 10,
    discount: 5,
    unit: 'quantity',
  },
  {
    id: 2,
    title: 'Amaron Pro Battery',
    productNum: 10123457,
    brand: 'Amaron',
    is_featured: true,
    batchNo: '12345679',
    category: 'Automotive Batteries',
    price: 160,
    quantity: 1,
    subtotal: 0,
    tax: 10,
    discount: 5,
    unit: 'quantity',
  },
  {
    id: 3,
    title: 'Bosch S5 Battery',
    productNum: 10123458,
    brand: 'Bosch',
    is_featured: true,
    batchNo: '12345680',
    category: 'Automotive Batteries',
    price: 170,
    quantity: 1,
    subtotal: 0,
    tax: 10,
    discount: 5,
    unit: 'quantity',
  },
  {
    id: 4,
    title: 'Trojan T-105 Battery',
    productNum: 10123459,
    brand: 'Trojan',
    is_featured: true,
    batchNo: '12345681',
    category: 'Industrial Batteries',
    price: 180,
    quantity: 1,
    subtotal: 0,
    tax: 15,
    discount: 5,
    unit: 'quantity',
  },
  {
    id: 5,

    title: 'Duracell CopperTop AA',
    productNum: 10123460,
    brand: 'Duracell',
    is_featured: false,
    batchNo: '12345682',
    category: 'Consumer Batteries',
    price: 10,
    quantity: 4,
    subtotal: 0,
    tax: 1,
    discount: 1,
    unit: 'pack',
  },
  {
    id: 6,
    title: 'Energizer Rechargeable AA',
    productNum: 10123461,
    brand: 'Energizer',
    is_featured: true,
    batchNo: '12345683',
    category: 'Consumer Batteries',
    price: 20,
    quantity: 4,
    subtotal: 0,
    tax: 2,
    discount: 1,
    unit: 'pack',
  },
  {
    id: 7,

    title: 'Tesla Powerwall',
    productNum: 10123462,
    brand: 'Tesla',
    is_featured: true,
    batchNo: '12345684',
    category: 'Renewable Energy Batteries',
    price: 5000,
    quantity: 1,
    subtotal: 0,
    tax: 250,
    discount: 100,
    unit: 'unit',
  },
  {
    id: 8,
    title: 'Michelin Primacy All-Season',
    productNum: 10123463,
    brand: 'Michelin',
    is_featured: true,
    batchNo: '12345685',
    category: 'Passenger Tyres',
    price: 200,
    quantity: 1,
    subtotal: 0,
    tax: 10,
    discount: 5,
    unit: 'tyre',
  },
  {
    id: 9,
    title: 'Bridgestone Turanza All-Season',
    productNum: 10123464,
    brand: 'Bridgestone',
    is_featured: true,
    batchNo: '12345686',
    category: 'Passenger Tyres',
    price: 210,
    quantity: 1,
    subtotal: 0,
    tax: 10,
    discount: 5,
    unit: 'tyre',
  },
  {
    id: 10,
    title: 'Goodyear Assurance All-Season',
    productNum: 10123465,
    brand: 'Goodyear',
    is_featured: true,
    batchNo: '12345687',
    category: 'Passenger Tyres',
    price: 220,
    quantity: 1,
    subtotal: 0,
    tax: 10,
    discount: 5,
    unit: 'tyre',
  },
  {
    id: 11,
    title: 'Michelin Pilot Sport Summer',
    productNum: 10123466,
    brand: 'Michelin',
    is_featured: true,
    batchNo: '12345688',
    category: 'Passenger Tyres',
    price: 230,
    quantity: 1,
    subtotal: 0,
    tax: 15,
    discount: 5,
    unit: 'tyre',
  },
  {
    id: 12,

    title: 'Bridgestone Potenza Summer',
    productNum: 10123467,
    brand: 'Bridgestone',
    is_featured: true,
    batchNo: '12345689',
    category: 'Passenger Tyres',
    price: 240,
    quantity: 1,
    subtotal: 0,
    tax: 15,
    discount: 5,
    unit: 'tyre',
  },
  {
    id: 13,

    title: 'Pirelli P Zero Summer',
    productNum: 10123468,
    brand: 'Pirelli',
    is_featured: true,
    batchNo: '12345690',
    category: 'Passenger Tyres',
    price: 250,
    quantity: 1,
    subtotal: 0,
    tax: 15,
    discount: 5,
    unit: 'tyre',
  },
  {
    id: 14,

    title: 'Michelin X-Ice Winter',
    productNum: 10123469,
    brand: 'Michelin',
    is_featured: true,
    batchNo: '12345691',
    category: 'Passenger Tyres',
    price: 260,
    quantity: 1,
    subtotal: 0,
    tax: 20,
    discount: 5,
    unit: 'tyre',
  },
  {
    id: 15,

    title: 'Bridgestone Blizzak Winter',
    productNum: 10123470,
    brand: 'Bridgestone',
    is_featured: true,
    batchNo: '12345692',
    category: 'Passenger Tyres',
    price: 270,
    quantity: 1,
    subtotal: 0,
    tax: 20,
    discount: 5,
    unit: 'tyre',
  },
  {
    id: 16,
    title: 'Goodyear Ultra Grip Winter',
    productNum: 10123471,
    brand: 'Goodyear',
    is_featured: true,
    batchNo: '12345693',
    category: 'Passenger Tyres',
    price: 280,
    quantity: 1,
    subtotal: 0,
    tax: 20,
    discount: 5,
    unit: 'tyre',
  },
];

export default product_data;
